#SUM을 해주지 않으면 GROUP BY를 해주지 않은 결과물에서 연산하기때문에 액수가 이상하게 나온다.
SELECT P.PRODUCT_CODE, SUM(P.PRICE*O.SALES_AMOUNT) AS SALES
FROM PRODUCT P JOIN OFFLINE_SALE O USING (PRODUCT_ID)
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE;